# Generated by Django 5.1.7 on 2025-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_remove_offrecovoiturage_date_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecovoiturage',
            name='latitude_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecovoiturage',
            name='latitude_depart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecovoiturage',
            name='longitude_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecovoiturage',
            name='longitude_depart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecovoiturage',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('matched', 'Matching trouvé'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='offrecovoiturage',
            name='latitude_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrecovoiturage',
            name='latitude_depart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrecovoiturage',
            name='longitude_arrivee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrecovoiturage',
            name='longitude_depart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrecovoiturage',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=20),
        ),
    ]
