# Generated by Django 5.1.7 on 2025-06-19 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_demandecovoiturage_latitude_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecovoiturage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offrecovoiturage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
